## Tensor 

In [65]:
import torch
import numpy as np
# torch.manual_seed(7)

### Define Tensor
    - Fundamental Data Structure of PyTorch
    - Multi-dimensional Array

In [78]:
# torch.manual_seed(7)
x = torch.rand(6, 4)
print(x)

# x = torch.zeros(6, 4, dtype=torch.long)
# print(x)

# x = torch.tensor([6.4, 4.6])
# print(x)

tensor([[0.5209, 0.5932, 0.8797, 0.6286],
        [0.7653, 0.1132, 0.8559, 0.6721],
        [0.6267, 0.5691, 0.7437, 0.9592],
        [0.3887, 0.2214, 0.3742, 0.1953],
        [0.7405, 0.2529, 0.2332, 0.9314],
        [0.9575, 0.5575, 0.4134, 0.4355]])


In [77]:
# Get size and datatype of tensor

print(x.size(), x.shape, x.dtype)


torch.Size([2]) torch.Size([2]) torch.float32


### Operations on PyTorch

In [82]:
y = torch.rand(6, 4)
# print(x + y)

# print(torch.add_(x, y, ))

# result = torch.empty(6, 4)
# torch.add(x, y, out=result)
# print(result)

# y.add_(x)
# print(y)



tensor([[1.1208, 0.8855, 1.7057, 0.8504],
        [1.3662, 0.4704, 0.9222, 0.8465],
        [1.3309, 1.2669, 0.9346, 1.3033],
        [0.4213, 0.9902, 1.3065, 0.8588],
        [0.9311, 1.0166, 1.1481, 1.3291],
        [1.3756, 1.2306, 0.9777, 0.7702]])


### NumPy and PyTorch


In [89]:
a = torch.ones(5)
print(a.dtype)

# b = a.numpy()
# print(b)

a = np.ones(5)
b = torch.from_numpy(a)
# np.add(a, 1, out=a)
print(a.dtype)
print(b.dtype)
# print(torch)

torch.float32
float64
torch.float64


### CUDA Tensors

In [90]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.5209, 1.5932, 1.8797, 1.6286],
        [1.7653, 1.1132, 1.8559, 1.6721],
        [1.6267, 1.5691, 1.7437, 1.9592],
        [1.3887, 1.2214, 1.3742, 1.1953],
        [1.7405, 1.2529, 1.2332, 1.9314],
        [1.9575, 1.5575, 1.4134, 1.4355]], device='cuda:0')
tensor([[1.5209, 1.5932, 1.8797, 1.6286],
        [1.7653, 1.1132, 1.8559, 1.6721],
        [1.6267, 1.5691, 1.7437, 1.9592],
        [1.3887, 1.2214, 1.3742, 1.1953],
        [1.7405, 1.2529, 1.2332, 1.9314],
        [1.9575, 1.5575, 1.4134, 1.4355]], dtype=torch.float64)


# AUTOGRAD: Automatic Differentiation

In [114]:
x = torch.ones(2, 2, requires_grad=True)
print(x.grad)

None


In [115]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [116]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [29]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [122]:
# out.backward()
out.backward(retain_graph=True)
print(x.grad, out)

tensor([[27., 27.],
        [27., 27.]]) tensor(27., grad_fn=<MeanBackward0>)


In [112]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


![Gradient Computation](../img/gradient.jpg)

    - with .requires_grad as True, it starts to track all operations on it and to stop tracking value can be set to False
    - to remove tensor from computational graph x.detach() can also be used.
    - torch.no_grad() will stop autograd engine to stop calculating gradients or backward pass.
    